apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-ai
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result > 0.90
    provider:
      plugin:
        argoproj-labs/metric-ai:
          agentUrl: http://kubernetes-agent:8080
          baseBranch: main
          githubUrl: https://github.com/kevindubois/progressive-delivery
